language: ruby
rvm:
 - 2.3.0
 - jruby
 - rbx-2

services:
- postgresql

# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: rake db:{create, migrate, seed}
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: bundle exec rspec
